### ISSUE TITLE
track_EDA

### ISSUE THREAD

**Issue by minsv** [jihoon1990/Music_Popularity_Prediction#11]
EDA할때, track, album, artist로 나눠서 distplot 그리면 어떨까요?

[track] 
- track_id
- track_duration
- track_favorites
- track_genre_top
- track_listens
- track_title

[album]
- album_favorites
- album_id
- album_listens
- album_type

[artist]
- artist_favorites
- artist_id
- artist_name
      

u'title',
u'split', 
u'subset',
u'bit_rate',

**Comment by jihoon1990** [comment]
넵 말씀하신대로 주제별로 묶는게 좋을 것 같습니다.  그러면 draw 함수들이 모여있으니깐 말씀하신 순서로 변경부탁드릴게요~

**Comment by jihoon1990** [comment]
#16 에서 처리됨.
